# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/edgardog/Verilog/RISC-V2p/RISC-V2p.srcs/sources_1/bd/SharedRAM/ip/SharedRAM_blk_mem_gen_0_0/SharedRAM_blk_mem_gen_0_0.xci
# IP: The module: 'SharedRAM_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/edgardog/Verilog/RISC-V2p/RISC-V2p.gen/sources_1/bd/SharedRAM/ip/SharedRAM_blk_mem_gen_0_0/SharedRAM_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SharedRAM_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/edgardog/Verilog/RISC-V2p/RISC-V2p.srcs/sources_1/bd/SharedRAM/ip/SharedRAM_blk_mem_gen_0_0/SharedRAM_blk_mem_gen_0_0.xci
# IP: The module: 'SharedRAM_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/edgardog/Verilog/RISC-V2p/RISC-V2p.gen/sources_1/bd/SharedRAM/ip/SharedRAM_blk_mem_gen_0_0/SharedRAM_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SharedRAM_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
