#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Mar 13 17:49:59 -03 2023
# SW Build 3671981 on Fri Oct 14 04:59:54 MDT 2022
#
# IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim RISCV2P_TB_func_synth -key {Post-Synthesis:sim_1:Functional:RISCV2P_TB} -tclbatch RISCV2P_TB.tcl -protoinst "protoinst_files/SharedRAM.protoinst" -protoinst "protoinst_files/Adder.protoinst" -protoinst "protoinst_files/Subtracter.protoinst" -protoinst "protoinst_files/InstructionMemory.protoinst" -view /home/edgardog/Verilog/RISC-V2p/RISCV2P_TB_behav.wcfg -log simulate.log"
xsim RISCV2P_TB_func_synth -key {Post-Synthesis:sim_1:Functional:RISCV2P_TB} -tclbatch RISCV2P_TB.tcl -protoinst "protoinst_files/SharedRAM.protoinst" -protoinst "protoinst_files/Adder.protoinst" -protoinst "protoinst_files/Subtracter.protoinst" -protoinst "protoinst_files/InstructionMemory.protoinst" -view /home/edgardog/Verilog/RISC-V2p/RISCV2P_TB_behav.wcfg -log simulate.log

